### ISSUE TITLE
Dataset processing problem

### ISSUE THREAD

**Issue by eric1anderson** [OpenMatch/TASTE#10]
Hi,
I am looking to reproduce your data files that you provided in your google drive (train.txt, valid.txt etc) from scratch starting from the .inter and .item files. For Amazon Toys and Games dataset, I followed your instructions by going to the DIF-SR project and swapping in the run_recbole function you provided in the gen_dataset_example.py file then ran DIF-SR.sh.  I encountered an error when converting the category id (cid) around line 90 of this file where it says:
```
 File "/DIF-SR/recbole/quick_start/quick_start.py", line 91, in run_recbole
      cid = int(cid)

TypeError: only size-1 arrays can be converted to Python scalars
```
I tried removing this integer conversion line. However, the output of the item.txt is a bit different than the one you have in your google drive. The one I generated has a 0th item and a lot of padding everywhere:

Item.txt from Google Drive:
```
item_id	item_name	categories	brand	price	sales_rank
1	Little Red Tool Box: Magnetic Tabletop Learning Easel	'Toys & Games', 'Pretend Play', 'Dress Up & Pretend Play', 'Magnet & Felt Playboards'	Scholastic	16.19	369185
2	Dover Publications-Decorative Tile Designs Coloring Book	'Toys & Games', 'Arts & Crafts', 'Drawing & Sketch Pads', 'Drawing & Painting Supplies'	Dover Pubns	1.44	1009
```
My item.txt:
```
item_id	item_name	categories	brand	price	sales_rank
0	[PAD]	['[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]'
 '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]'
 '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]'
 '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]'
 '[PAD]' '[PAD]']	[PAD]	30.08	369185
1	Little Red Tool Box: Magnetic Tabletop Learning Easel	["'Toys" '&' "Games'," "'Pretend" "Play'," "'Dress" 'Up' '&' 'Pretend'
 "Play'," "'Magnet" '&' 'Felt' "Playboards'" '[PAD]' '[PAD]' '[PAD]'
 '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]'
 '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]'
 '[PAD]' '[PAD]' '[PAD]']	Scholastic	16.19	369185
2	Dover Publications-Decorative Tile Designs Coloring Book	["'Toys" '&' "Games'," "'Arts" '&' "Crafts'," "'Drawing" '&' 'Sketch'
 "Pads'," "'Drawing" '&' 'Painting' "Supplies'" '[PAD]' '[PAD]' '[PAD]'
 '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]'
 '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]' '[PAD]'
 '[PAD]' '[PAD]' '[PAD]']	Dover Pubns	1.44	1009
```
Is there some step that I potentially over looked? I suspect I did not handle that cid = int(cid) line correctly

I would super appreciate your input

**Comment by mssssss123** [comment]
Hello, 
I just tried to run the data processing code. But I didn't encounter the problem you mentioned. Can you provide me with more information so I can help you solve it?

The following are screenshots of my local computer running, I hope they can be of some help.

<img width="1503" alt="截屏2024-03-09 16 25 32" src="https://github.com/OpenMatch/TASTE/assets/56372416/2b0b5bf5-84f0-4dd7-89f6-bd75a1453dc9">

<img width="972" alt="截屏2024-03-09 16 27 44" src="https://github.com/OpenMatch/TASTE/assets/56372416/513b02fb-2f63-45c3-9cd3-d33026183938">

<img width="1499" alt="截屏2024-03-09 16 29 23" src="https://github.com/OpenMatch/TASTE/assets/56372416/40fb6ea1-c509-4dde-b881-181b9c942b94">


This is the processed data file generated by the code I just ran. In actual use, I deleted item 0 because it has no practical significance.

<img width="1526" alt="截屏2024-03-09 16 33 47" src="https://github.com/OpenMatch/TASTE/assets/56372416/2c177932-6948-4c24-b916-b33b3291623c">

**Comment by mssssss123** [comment]
Sorry, I just thought of a detail I dealt with earlier and forgot to mention. You need to modify the .inter and .item files and change their categories to token not token_seq so that they can form complete text.

<img width="1079" alt="截屏2024-03-09 16 45 41" src="https://github.com/OpenMatch/TASTE/assets/56372416/576d39da-0f6a-43fb-8865-322d3a10a928">


<img width="1079" alt="截屏2024-03-09 16 45 47" src="https://github.com/OpenMatch/TASTE/assets/56372416/68062459-419f-4299-ba48-de1a7b07c5a3">

Thank you very much for your report on the above problem. I will update the details of data processing in the next time.😊

**Comment by eric1anderson** [comment]
That worked! Thank you so much
