### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by ananv21** [OpenMatch/TASTE#7]
Hello,

Is it possible for me to use some other pretrained model in place of the T5 model to generate the embeddings? Or is the code written in such a way that the pretrained model has to be the T5 model?

Thank you!

**Comment by mssssss123** [comment]
Hello,

I think this is feasible because our modeling method based on text matching is similar to dense retrieval, and of course it can be replaced with other pre-trained models.

But my model code is only for T5, and this long text modeling method is also based on such an encoder-decoder architecture. Therefore I suggest you rewrite the model based on this framework. As for other parts, I think it can be adapted without modification.
