### ISSUE TITLE
About evaluation during training

### ISSUE THREAD

**Issue by tangzuoli** [OpenMatch/TASTE#8]
The evaluation step is set to 5000 step in the model, while I follow your steps, I meet a problem in the validation during the training. I read your code and find that there is no prediction_step function in your trainer code which may result in a list error
(a dictionary is need in the prediction_step while the inputs of your model is a list). I'm wondering should i set the eval_steps to 0 to make sure there is no validtion during the training and find the best ckeckpoint by the evaluate bash.

**Comment by mssssss123** [comment]
Hi,

Based on your description, I think you may have the same problem like #3. This is a problem caused by the Transformer version being too high. Using versions below 4.24.0 should not have this problem.

Of course, it's also a workaround if you don't use evaluation during training.

Hope this helps you solve this problem!😊

**Comment by tangzuoli** [comment]
Thank you for your prompt response! I'm sorry that I didn't browse through the closed issues.
